---
title: Data Cleaning
format: typst
---


```{r}
#| message: false
#| warning: false
#| fig.show: "hide"

#data/g24_sov_by_g24_svprec.csv: vote totals by precinct and contest
#data/g24-results-by-district.xlsx: aggregates votes to the congressional district level
#g24-candidates-by-district.csv: lists candidates running in each district

library(tidyverse)
library(readxl)
library(readr)
library(stringr)
library(sf)
library(dplyr)

#load the data 
#cleaning it by fixing the weird values 
prec <- read_csv('data/g24_sov_by_g24_svprec.csv', na = c("", "NA", "***", "*****"), show_col_types = FALSE)

#only wnt a couple of columns from this dataset
#we want precinct key, county FIPS, assembly / congressional district IDs, and the house results

#now lets clean the dataset 
prec_clean <- prec |>
    select(COUNTY, FIPS, SVPREC_KEY, ADDIST, CDDIST, TOTVOTE, DEMVOTE, REPVOTE, USPDEM01, USPREP01)

#save the cleaned dataset
write_csv(prec_clean, "data/clean-precinct.csv")

#district level data
dist <- read_excel("data/g24-results-by-district.xlsx", sheet = 1, col_names = FALSE)

#give names to col 
names(dist)[1:3] <- c("label", "dem", "rep")


dist_clean <- dist |>
    mutate(label = str_trim(label)) |>
    filter(label == "District Totals") |>
    transmute(
        district = row_number(),
        d_votes = as.numeric(dem),
        r_votes = as.numeric(rep)) 

write_csv(dist_clean, "data/clean-district-totals.csv")

```


```{r}
#reading csv 
sr_votes <- read_csv(
    "data/state_g24_sov_data_by_g24_srprec.csv",
    na = c("", "NA", "", "**", "****", "***", "*****"),
    show_col_types = FALSE
    ) |>
    select(SRPREC, USPDEM01, USPREP01) |>
    mutate(
        USPDEM01 = as.numeric(USPDEM01), 
        USPREP01 = as.numeric(USPREP01))

sr_shp <- st_read("data/shapefiles/srprecincts/srprec_state_g24_v01_shp.shp", quiet = TRUE)
ab604 <- st_read("data/shapefiles/AB604/AB604.shp", quiet = TRUE)

sr_shp <- sr_shp |>
    st_transform(3310) |>
    st_set_precision(1) |>
    st_make_valid() |>
    st_collection_extract("POLYGON")

ab604 <- ab604 |> 
    st_transform(3310) |>
    st_set_precision(1) |>
    st_make_valid() |>
    st_collection_extract("POLYGON")

sr <- sr_shp |>
    left_join(sr_votes, by = c("SRPREC" = "SRPREC")) |>
    mutate(area = st_area(geometry))

inter <- st_intersection(sr, ab604 |> select(new_dist = 1))

inter <- inter |>
    mutate(
        area2 = st_area(geometry),
        share = as.numeric(area2 / area),
        dem_s = share * USPDEM01,
        rep_s = share * USPREP01)

ab604_v <- inter |>
    st_drop_geometry() |>
    group_by(new_dist) |>
    summarize(
        dem = sum(dem_s, na.rm = TRUE),
        rep = sum(rep_s, na.rm = TRUE),
        .groups = "drop"
    ) |>
    mutate(total = dem + rep)

write_csv(ab604_v, "data/ab604-district-totals.csv")
```